Fix varint reading and writing. Closes #141
Dinnerbone/mcstatus pull request #142
Opened 2021-06-17 00:50 UTC by CoolCat467

Make varint reading and writing functions use C int 32's with ctypes module.
Important: Writing converts value to unsigned_int32, so that signed bit get forced to turn into a part of the number for writing, sort of breaking the number so python handles it like Java and C would. Reading converts final value back to signed_int32 so that the number is correct when python tries to use it.

2021-06-17 01:09 UTC, kevinkjt2000 requested changes
I have no familiarity with this myself, so I'm going to have to research this too in order to properly review this. Thanks for submitting a PR! Welcome to the club.

I cannot accept this until the tests are also passing. Please run the tests with `tox` :)
```
__________________________________________ TestConnection.test_readBigVarInt __________________________________________

self = <test_connection.TestConnection object at 0x000001F7D19AE550>

    def test_readBigVarInt(self):
        self.connection.receive(bytearray.fromhex("FFFFFFFF7F"))

>       assert self.connection.read_varint() == 34359738367
E       assert -1 == 34359738367
E         +-1
E         -34359738367

mcstatus\tests\protocol\test_connection.py:59: AssertionError
_______________________________________ TestConnection.test_writeInvalidVarInt ________________________________________

self = <test_connection.TestConnection object at 0x000001F7D19D7A60>

    def test_writeInvalidVarInt(self):
        with pytest.raises(ValueError):
>           self.connection.write_varint(34359738368)
E           Failed: DID NOT RAISE <class 'ValueError'>

mcstatus\tests\protocol\test_connection.py:74: Failed
```
https://github.com/Dinnerbone/mcstatus/blob/5320c870c59cf1d52d8e986f0da2e8a8b55aa4e5/mcstatus/tests/protocol/test_connection.py#L46-L74

2021-06-17 01:39 UTC, CoolCat467 commented
I think your tests are not working quite right my friend. Your first test my change failed is looking for the value 34359738367, which is 2 ** 35 - 1. This value is far larger than 2 ** 32 - 1. The second test my change failed is looking for the code to fail at values greater than 2 ** 35 - 1, in particular it's feeding it exactly 2 ** 35, 1 off from the previous bugged limit. 32 bit signed integers can only represent integers from -2147483648 to 2147483647.

2021-06-17 01:59 UTC, kevinkjt2000 commented
Of course, you may change the tests to be correct. When I say that I can't accept code without tests passing, I mean that if the tests can't pass I can't run the release script which runs the tests:

https://github.com/Dinnerbone/mcstatus/blob/5320c870c59cf1d52d8e986f0da2e8a8b55aa4e5/release.sh#L4

2021-06-17 02:23 UTC, CoolCat467 commented
#144 should fix tests to look for feasible values and also test negative varints

2021-06-21 15:15 UTC, merged

2021-06-21 16:06 UTC, kevinkjt2000 commented
Released in v6.1.2
Thanks for the contribution ❤️